version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xray-backend
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MODEL_PATH=/app/checkpoints/best_model.pth
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    restart: unless-stopped
    networks:
      - xray-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xray-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - xray-network

networks:
  xray-network:
    driver: bridge

volumes:
  checkpoints:
  data:
  logs:
